### ISSUE TITLE
OnSuccess callback missing

### ISSUE THREAD

**Issue by ouya99** [datatrans/react-datatrans-light-box#17]
Hello,

we are working with the datatrans lightbox and we need a "real" callback (not just a redirect URL) after a successful payment method cause we are using the lightbox inside an iframe webshop without access to the wrapper host page.

Please help. Thank you!

**Comment by pstadler** [comment]
This is not really possible because most relevant payment methods perform redirects (3D authentication, PayPal, PostFinance, ...)

**Comment by pstadler** [comment]
If you have further questions please write to support@datatrans.ch.

**Comment by ouya99** [comment]
you can add parameter uppReturnTarget=_self, to get a redirect back to your iframe

**Comment by dmengelt** [comment]
Hi @ouya99 
Yes you are right you can use that. However, we usually do not recommend that. Also, even with `uppReturnTarget=_self` it is still a redirect. As @pstadler already mentioned we do not provide a real callback because almost all payment flows (especially the 3D process for credit cards) need a redirect.
